<a href="https://colab.research.google.com/github/Vijaynaik22-7/4IK25CS239_DAV_LAB/blob/main/4ik25cs239_exp_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([2,3,4,5])
new = arr+5
print(new)
print(arr)

[ 7  8  9 10]
[2 3 4 5]


In [ ]:
print(arr[2])

4


In [ ]:
print(arr[0])

2


In [ ]:
print(arr[-1])

5


In [ ]:
print(arr[0:2])

[2 3]


In [ ]:
print(arr[-1:-3])

[]


In [ ]:
print(arr[-3:-1])

[3 4]


In [ ]:
print(arr+arr)

[ 4  6  8 10]


In [ ]:
sqr = arr*arr
print(sqr)

[ 4  9 16 25]


In [ ]:
mul2 = arr*2
print(mul2)

[ 4  6  8 10]


In [ ]:
np.sum(arr)

14

In [ ]:
np.mean(arr)

3.5

In [ ]:
np.min(arr)

2

In [ ]:
np.max(arr)

5

In [ ]:
np.sqrt(arr)

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
a = arr.reshape(2,2)

In [ ]:
print(a)

[[2 3]
 [4 5]]


In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
student = {
    "name": ["Nayeem", "Mahtab", "Mahesh", "Nagaraj", "Mutturaj"],
    "age": [19, 21, 20, 23, 22],
    "course": ["CSE", "Mech", "ECE", "EEE", "AIML"]
}


In [ ]:
print(student)

{'name': ['Nayeem', 'Mahtab', 'Mahesh', 'Nagaraj', 'Mutturaj'], 'age': [19, 21, 20, 23, 22], 'course': ['CSE', 'Mech', 'ECE', 'EEE', 'AIML']}


In [ ]:
data = pd.DataFrame(student)
print(data)

       name  age course
0    Nayeem   19    CSE
1    Mahtab   21   Mech
2    Mahesh   20    ECE
3   Nagaraj   23    EEE
4  Mutturaj   22   AIML


In [ ]:
print(data["name"])

0      Nayeem
1      Mahtab
2      Mahesh
3     Nagaraj
4    Mutturaj
Name: name, dtype: object


In [ ]:
print(data["age"])

0    19
1    21
2    20
3    23
4    22
Name: age, dtype: int64


In [ ]:
print(data["course"])

0     CSE
1    Mech
2     ECE
3     EEE
4    AIML
Name: course, dtype: object


In [ ]:
print(data.iloc[0])

name      Nayeem
age           19
course       CSE
Name: 0, dtype: object


In [ ]:
print(data.iloc[1:3])

     name  age course
1  Mahtab   21   Mech
2  Mahesh   20    ECE


In [ ]:
print(data.iloc[1,2])

Mech


In [ ]:
print(data.iloc[1,1])

21


In [ ]:
print(data[data["age"]>20])

       name  age course
1    Mahtab   21   Mech
3   Nagaraj   23    EEE
4  Mutturaj   22   AIML


In [ ]:
print(data[(data["age"]>20) & (["course"] == "CSE")])

Empty DataFrame
Columns: [name, age, course]
Index: []


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr2d*arr2d)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
